export const USER_ACTION_TYPES = {
  LOGIN_USER_START: "LOGIN_USER_START",
  LOGIN_USER_SUCCESS: "LOGIN_USER_SUCCESS",
  LOGIN_USER_FAILURE: "LOGIN_USER_FAILURE",
  LOGOUT_USER: "LOGOUT_USER",
  UPDATE_SETTINGS_START: "UPDATE_SETTINGS_START",
  UPDATE_SETTINGS_SUCCESS: "UPDATE_SETTINGS_SUCCESS",
  UPDATE_SETTINGS_FAILURE: "UPDATE_SETTINGS_FALIURE",
  SIGNUP_USER_START: "SIGNUP_USER_START",
  SIGNUP_USER_SUCCESS: "SIGNUP_USER_SUCCESS",
  SIGNUP_USER_FAILURE: "SIGNUP_USER_FAILURE",
};
